name: Github Action Build PKGBUILD
on: push
jobs:
  build_for_arch:
    runs-on: ubuntu-latest
    steps:
      - name: Build linux-ck-uksm for arch
        uses: antman666/build-aur-action@mine
        with:
          repo-name: own_kernel
      - uses: ncipollo/release-action@v1.8.6
        with:
          allowUpdates: true
          tag: "v5.12.19-3_gcc"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
