name: Github Action Build PKGBUILD
on:
  push:
  workflow_dispatch:
jobs:
  build_antman:
    runs-on: ubuntu-latest
    steps:
      - name: Build linux-antman for arch
        uses: actions/checkout@v2.3.4
      - id: makepkg
        uses: antman666/pkgbuild-action@mine
        with:
          pkgdir: "linux"
          namcapDisable: 1
          makepkgArgs: "--skippgpcheck"
          aurDeps: 1
      - uses: ncipollo/release-action@v1.8.6
        with:
          allowUpdates: true
          tag: "x86_64"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
  build_ck_uksm:
    runs-on: ubuntu-latest
    steps:
      - name: Build linux-ck-uksm for arch
        uses: actions/checkout@v2.3.4
      - id: makepkg
        uses: antman666/pkgbuild-action@mine
        with:
          pkgdir: "linux-ck-uksm"
          namcapDisable: 1
          makepkgArgs: "--skippgpcheck"
          aurDeps: 1
      - uses: ncipollo/release-action@v1.8.6
        with:
          allowUpdates: true
          tag: "x86_64"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
  build_xanmod_cacule_uksm:
    runs-on: ubuntu-latest
    steps:
      - name: build linux-xanmod-cacule-uksm for arch
        uses: actions/checkout@v2.3.4
      - id: makepkg
        uses: antman666/pkgbuild-action@mine
        with:
          pkgdir: "linux-xanmod-cacule-uksm"
          namcapDisable: 1
          makepkgArgs: "--skippgpcheck"
          aurDeps: 1
      - uses: ncipollo/release-action@v1.8.6
        with:
          allowUpdates: true
          tag: "x86_64"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
  build_clear:
    runs-on: ubuntu-latest
    steps:
      - name: Build linux-ck-uksm for arch
        uses: actions/checkout@v2.3.4
      - id: makepkg
        uses: antman666/pkgbuild-action@mine
        with:
          pkgdir: "linux-clear"
          namcapDisable: 1
          makepkgArgs: "--skippgpcheck"
          aurDeps: 1
      - uses: ncipollo/release-action@v1.8.6
        with:
          allowUpdates: true
          tag: "x86_64"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
  update_db:
    needs: [build_antman, build_ck_uksm, build_xanmod_cacule_uksm, build_clear]
    runs-on: ubuntu-latest
    steps: 
      - uses: antman666/update-db-for-repo@mine
        with: 
          tag: x86_64
      - uses: ncipollo/release-action@v1.8.6
        with:
          allowUpdates: True
          tag: "x86_64"
          artifacts: "./own-kernels.*"
          token: ${{ secrets.GITHUB_TOKEN }}

