name: Github Action Build PKGBUILD
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        packages: [v2raya-git]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Build packages for arch
        uses: actions/checkout@v3.0.2
      - id: makepkg
        uses: antman666/pkgbuild-action@non-lto
        with:
          pkgdir: ${{ matrix.packages }}
          namcapDisable: 1
          makepkgArgs: "--skippgpcheck"
      - uses: ncipollo/release-action@v1.10.0
        with:
          allowUpdates: true
          tag: "x86_64"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
  update_db:
    needs: [build]
    runs-on: ubuntu-latest
    steps: 
      - uses: antman666/update-db-for-repo@mine
        with: 
          tag: x86_64
      - uses: ncipollo/release-action@v1.10.0
        with:
          allowUpdates: True
          tag: "x86_64"
          artifacts: "./own-repo.*"
          token: ${{ secrets.GITHUB_TOKEN }}

